Set-Variable -Name 零 -Value 0 -Scope global -Option ReadOnly -Force
Set-Variable -Name 一 -Value 1 -Scope global -Option ReadOnly -Force
Set-Variable -Name 二 -Value 2 -Scope global -Option ReadOnly -Force
Set-Variable -Name 三 -Value 3 -Scope global -Option ReadOnly -Force
Set-Variable -Name 四 -Value 4 -Scope global -Option ReadOnly -Force
Set-Variable -Name 五 -Value 5 -Scope global -Option ReadOnly -Force
Set-Variable -Name 六 -Value 6 -Scope global -Option ReadOnly -Force
Set-Variable -Name 七 -Value 7 -Scope global -Option ReadOnly -Force
Set-Variable -Name 八 -Value 8 -Scope global -Option ReadOnly -Force
Set-Variable -Name 九 -Value 9 -Scope global -Option ReadOnly -Force
Set-Variable -Name 十 -Value 10 -Scope global -Option ReadOnly -Force
